# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29a57478aaf86e6b9cf4f25f4854c7c9ecba02e3090134315e847183870b726378901b82db2c120001499aa88ef03189001bd7640635d2969615dfad0d8f74eb

test:
  secret_key_base: 60440fea6ea0ee1175c59bfc0dc1e082a37e147b8666cc720d39a0f56b034c2badcd252b479d5e869be35d967b477f6eaf8cf666fd2032bbc09e5347d68110e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
